import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, UploadCloud, CheckCircle2 } from 'lucide-react';
import { cn } from '../lib/utils';
import { useMirage } from '../hooks/useMirage';

interface PublishModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const PublishModal = ({ isOpen, onClose }: PublishModalProps) => {
  const [code, setCode] = useState('');
  const [isPublishing, setIsPublishing] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const { publishApp } = useMirage();

  const handlePublish = async () => {
    if (!code.trim()) return;
    
    setIsPublishing(true);
    try {
      const naddr = await publishApp(code, 'New Mirage App');
      console.log('Published app:', naddr);
      
      setIsSuccess(true);
      setTimeout(() => {
        onClose();
        setIsSuccess(false);
        setCode('');
      }, 2000);
    } catch (error) {
      console.error('Publishing failed:', error);
      alert('Publishing failed. Do you have a Nostr extension (NIP-07) installed?');
    } finally {
      setIsPublishing(false);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-6">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
          />
          
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            className="relative w-full max-w-2xl bg-[#18181B] border border-[#2E2E36] rounded-[32px] overflow-hidden shadow-2xl"
          >
            {/* Header */}
            <div className="p-8 pb-0 flex justify-between items-start">
              <div>
                <h2 className="text-2xl font-bold mb-1">Publish App</h2>
                <p className="text-gray-400 text-sm">Paste the HTML code generated by the AI.</p>
              </div>
              <button 
                onClick={onClose}
                className="p-2 hover:bg-white/5 rounded-full transition-colors text-gray-500 hover:text-white"
              >
                <X size={20} />
              </button>
            </div>

            {/* Content */}
            <div className="p-8">
              <div className="relative group">
                <textarea
                  value={code}
                  onChange={(e) => setCode(e.target.value)}
                  placeholder="<html>&#10;  <head>...</head>&#10;  <body>...</body>&#10;</html>"
                  className={cn(
                    "w-full h-64 bg-[#0F0F13] border border-[#2E2E36] rounded-2xl p-6",
                    "font-mono text-sm text-gray-400 outline-none transition-all focus:border-accent-primary",
                    "resize-none placeholder:text-gray-700"
                  )}
                />
                {!code && (
                  <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none opacity-20 group-hover:opacity-30 transition-opacity">
                    <UploadCloud size={48} className="mb-4" />
                    <span className="text-sm font-medium">Click to paste or drop file</span>
                  </div>
                )}
              </div>

              <div className="mt-8 flex items-center gap-4">
                <button
                  onClick={handlePublish}
                  disabled={!code.trim() || isPublishing || isSuccess}
                  className={cn(
                    "flex-1 py-4 rounded-2xl font-bold transition-all relative overflow-hidden",
                    !code.trim() 
                      ? "bg-gray-800 text-gray-500 cursor-not-allowed" 
                      : "bg-accent-gradient text-white shadow-accent-glow hover:shadow-accent-glow-hover active:scale-[0.98]"
                  )}
                >
                  <span className={cn("transition-opacity", (isPublishing || isSuccess) ? "opacity-0" : "opacity-100")}>
                    Sign & Publish Event
                  </span>
                  
                  {(isPublishing || isSuccess) && (
                    <div className="absolute inset-0 flex items-center justify-center">
                      {isPublishing ? (
                        <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      ) : (
                        <motion.div 
                          initial={{ scale: 0.5, opacity: 0 }}
                          animate={{ scale: 1, opacity: 1 }}
                          className="flex items-center gap-2"
                        >
                          <CheckCircle2 size={20} />
                          Success
                        </motion.div>
                      )}
                    </div>
                  )}
                </button>
                
                <button 
                  onClick={onClose}
                  className="px-8 py-4 bg-transparent border border-[#2E2E36] rounded-2xl font-bold hover:bg-white/5 transition-colors"
                >
                  Cancel
                </button>
              </div>
            </div>

            {/* Footer Status */}
            <div className="px-8 py-4 bg-[#141419] border-t border-[#2E2E36] flex justify-between items-center text-[10px] font-bold text-gray-600 uppercase tracking-widest">
              <span>Nostr Kind 30078</span>
              <span>Signed via NIP-07</span>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
